<a href="https://colab.research.google.com/github/Ratnakar-kaushal/Data-Science-/blob/main/SummerTraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Summer Training**

In [ ]:
print("hello")

hello


##To Do Arithmetic Operations.

##Addition, Substraction, Multiplication, Division

In [ ]:
A##Addition
a=int(input("Enter first number= "))
b=int(input("Enter second number= "))
c=a+b
print("Output= ",c)

Enter first number6
Enter second number4
Output=  10


In [ ]:
#Substraction
x=int(input("Enter first number= "))
y=int(input("Enter second number= "))
z=x-y
print("Output= ",c)

Enter first number= 27
Enter second number= 7
Output=  2


In [ ]:
#multiplication
p=int(input("Enter first number= "))
q=int(input("Enter second number= "))
r=p*q
print("Output= ",r)

Enter first number= 5
Enter second number= 4
Output=  20


In [ ]:
#division
d=int(input("Enter first number= "))
e=int(input("Enter second number= "))
f=d/e
print("Output= ",f)

Enter first number= 10
Enter second number= 2
Output=  5.0


#To Swap Two Numbers.

In [ ]:
a= int(input ("enter value of a= "))
b= int(input ("enter value of b= "))
a,b=b,a
print("value of a after swapping= ",a)
print("value of b after swapping= ",b)


enter value of a= 27
enter value of b= 24
value of a after swapping=  24
value of b after swapping=  27


##To Calculate Simple Intrest.

In [ ]:
p=int(input("enter principle "))
t=int(input("enter time "))
r=int(input("enter rate "))
s=(p*t*r)/100
print("simple intrest ",s)

enter principle 1000
enter time 3
enter rate 5
simple intrest  150.0


07/July/2022
Python Identifiers
Tuples
Reserved words: we are free to reassign thge reserved names and use them as variable. it generally is not a good idea.
We can reassign a function and also reassign a variable
for ex
my_print=print
here my_print is function
Tuples
x,y,z=100,-45,0
Better way for input
x=input("enter some text")
more better method
x=int(input("enter"))



In [ ]:
a=eval(input("enter an expression:"))
print(a)

enter an expression:2*4+6
14


In [ ]:
#controlling print statement
#separate the values of tuple
a,b,c,d=10,11,12,13
print(a,b,c,d,sep=':')
print(a,b,c,d,sep=';')
print(a,b,c,d)
print(a,b,c,d,sep="===")

10:11:12:13
10;11;12;13
10 11 12 13
10===11===12===13


In [ ]:
#operators
#unary-one operand
#binary 
#ternary-3 operators
x,y=5,7;
min=x if x<y else y;
print(min);

5


In [ ]:
#if condition syntax
#if cond:
  #statement
  #else:
  #statement

x1=int(input("first no"))
y1=int(input("2nd no"))
if x1>y1: 
  print("x1 is greater",x1)
else:
  print("y1 is greater",y1)
print("bye")

first no55
2nd no14
x1 is greater 55
bye


In [ ]:
a=True
b=False
print(a and b)
print(a or b)

False
True


In [ ]:
i=0
s=0;
while(i<5)
x=int(input("enter no))
s=s+x
i=i+1
print("sum is", s)

In [ ]:
choice=int(input("enteer your choice"))
#now use if/elif or switch 
if choice==1
condition
elif choice==2
contition
elif choice==3
condition

In [ ]:
#factorial
#modulus operator
'''
//
15//4 gives integer 3
16%5 gives 1... remiender
'''

#Program to find even and odd nos till 20 

In [ ]:
#print sum of even nos til 20
n=0
s=0
while(n<20)
print(n)
n=n+2;
print("done")

In [ ]:
armstrong
123
1cube+2cube+3cube=123 then it is armstrong 
sum of factors equal to number = perfect number

##WAP to find sum of digits of a number

In [3]:
#wap to find sum of digits of a number
s=0
num=int(input("enter"))
while(num>0):
  r=num%10   #r got remiender
  s=s+r     #initially s=0,r=5; s+r=5
  num=num//10   #num got 345/10=34
print("sum of digits of num", s)


enter54542
sum of digits of num 20


In [4]:
num=int(input("Enter a number="))
s=0
while temp>0:
    temp=num
    d=temp%10
    s+=d*d*d|
    temp//10
if(num==s):
    print("number is armstrong")
else:
    print("number is not armstrong")

SyntaxError: ignored

In [ ]:
s=0
num=int(input("enter"))
while num>0:
  r=num%10
  s=s+r     
  num=num//10
  print("sum of digits of num", s)
print('bye bye tata')

enter1254
sum of digits of num 4
sum of digits of num 9
sum of digits of num 11
sum of digits of num 12
bye bye tata


In [ ]:
s=0
num=int(input("enter"))
temp=num
while num>0:
  r=num%10
  s+=r**3
  num=num//10
print("armstrong", s)
if num==s:
  print("armstrong")
else:
  print("not armstrong")

enter153
armstrong 153
not armstrong


In [ ]:
12/07/2022
remove pop del 
tuples
packing
unpacking
list comorehension

In [ ]:
#13/07/2022
#Dictonary
#function
#calling function
#recurssion-function calling itself.


In [ ]:
#to find factorial
n=int(input('enter number'))
fact=1
if(n<0):
  print('no must be positive')
elif(n==0):
  print('fact=1')
else:
  for i in range(1,n+1):
   fact=fact*i
print(fact)

enter number4
24


In [ ]:
num=int(input('enter number='))
for i in range(1,11):
  print(num,'X',i,'=',num*i)

enter number=5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


In [ ]:
#to print address of a
a=10
print(a,id(a))


10 11256352


In [ ]:
import numpy as np

In [ ]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
b=np.array([[4,5],[44,55]])
print (b)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

[[ 4  5]
 [44 55]]
(2, 2)
2
4
int64


In [ ]:
c=np.arange(20).reshape(4,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
c1=c.reshape(10,2)
print(c1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
c3=np.arange(20).reshape(10,2)
c4=c1+c3
print(c4)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]]


In [ ]:
d=np.arange(4)
e=np.array([5,6,7,8])
print(d)
print(e)
f=d**e
g=d*2
h=d**2
print(f)
print(g)
print(h)

[0 1 2 3]
[5 6 7 8]
[   0    1  128 6561]
[0 2 4 6]
[0 1 4 9]


In [ ]:
aa=np.arange(12).reshape(2,2,3)
aa[:,1,1]
print(aa)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
import csv
import pandas as pd 

In [ ]:
from google.colab import files
uploaded=files.upload()
#df=pd.read_csv("C:\Users\pc\Desktop/Punjab.csv")

Saving Punjab.csv to Punjab.csv


In [ ]:
df=pd.read_csv("Punjab.csv")

In [ ]:
df.head(6)
df.describe

<bound method NDFrame.describe of            Date  Confirmed  Deceased  Recovered
0    2020-03-14          1         0          0
1    2020-03-15          0         0          0
2    2020-03-16          0         0          0
3    2020-03-17          0         0          0
4    2020-03-18          1         0          0
..          ...        ...       ...        ...
592  2021-10-27         38         2         16
593  2021-10-28         31         0         27
594  2021-10-29         29         1         25
595  2021-10-30         26         1         27
596  2021-10-31         26         1         25

[597 rows x 4 columns]>

In [ ]:
import pandas as pd
from google.colab import files
uploaded=files.upload()

Saving wineQualityReds.csv to wineQualityReds (1).csv


In [ ]:
df1=pd.read_csv('wineQualityReds.csv')

In [ ]:
df1.describe()
df1.head(10)



Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.4              0.70         0.00             1.9   
1           2            7.8              0.88         0.00             2.6   
2           3            7.8              0.76         0.04             2.3   
3           4           11.2              0.28         0.56             1.9   
4           5            7.4              0.70         0.00             1.9   
5           6            7.4              0.66         0.00             1.8   
6           7            7.9              0.60         0.06             1.6   
7           8            7.3              0.65         0.00             1.2   
8           9            7.8              0.58         0.02             2.0   
9          10            7.5              0.50         0.36             6.1   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   
5      0.075                 13.0                  40.0   0.9978  3.51   
6      0.069                 15.0                  59.0   0.9964  3.30   
7      0.065                 15.0                  21.0   0.9946  3.39   
8      0.073                  9.0                  18.0   0.9968  3.36   
9      0.071                 17.0                 102.0   0.9978  3.35   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5  
5       0.56      9.4        5  
6       0.46      9.4        5  
7       0.47     10.0        7  
8       0.57      9.5        7  
9       0.80     10.5        5

In [ ]:
df1.max()

<bound method NDFrame._add_numeric_operations.<locals>.max of       Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.4             0.700         0.00   
1              2            7.8             0.880         0.00   
2              3            7.8             0.760         0.04   
3              4           11.2             0.280         0.56   
4              5            7.4             0.700         0.00   
...          ...            ...               ...          ...   
1594        1595            6.2             0.600         0.08   
1595        1596            5.9             0.550         0.10   
1596        1597            6.3             0.510         0.13   
1597        1598            5.9             0.645         0.12   
1598        1599            6.0             0.310         0.47   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0                1.9      0.076                 11.0               

In [ ]:
##reading wines dataset from github.com
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"

In [ ]:
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)

In [ ]:
print(wfile[1:5])

[[      nan 7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01
  5.400e+01 9.970e-01 3.260e+00 6.500e-01 9.800e+00 5.000e+00]
 [      nan 1.120e+01 2.800e-01 5.600e-01 1.900e+00 7.500e-02 1.700e+01
  6.000e+01 9.980e-01 3.160e+00 5.800e-01 9.800e+00 6.000e+00]
 [      nan 7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01
  3.400e+01 9.978e-01 3.510e+00 5.600e-01 9.400e+00 5.000e+00]
 [      nan 7.400e+00 6.600e-01 0.000e+00 1.800e+00 7.500e-02 1.300e+01
  4.000e+01 9.978e-01 3.510e+00 5.600e-01 9.400e+00 5.000e+00]]


In [ ]:
print(wfile[:,1].max())

15.9


In [ ]:
print(wfile.shape)

(1598, 13)


In [ ]:
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)
def largenumber(x):
  if x>0:
    print(wfile[:,x].max())
  #print(wfile[:,x].max())
d=int(input(x))
largenumber(d)

1
15.9


In [ ]:
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)
def number(x):
 # if x>0:
 #   print(wfile[:,x].max())
  #print(wfile[:,x].max())
def choice(a):
  if a==1:
    d=int(input(x))
    print(wfile[:,x].max())
  elif a==0:
    print(wfile[:,x].min())
a=0
input(a)
number(d)
#d=int(input(x))
#largenumber(d)

IndentationError: ignored

In [ ]:
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)
def number(x):
  def choice(a):
    if a==1:
     # d=int(input(x))
      print(wfile[:,x].max())
    elif a==0:
     # d=int(input(x))
      print(wfile[:,x].min())
s=int(input(a))
d=int(input(x))
number(d)
choice(s)


1
1
4
nan


In [ ]:
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)
'''
def largenumber(x):
  if x>0:
    print(wfile[:,x].max())
  #print(wfile[:,x].max())
d=int(input(x))
largenumber(d)
'''
i=1
while(i<13):
  print(wfile[:,i].max())
  print(wfile[:,i].min())
  i+=1


15.9
4.6
1.58
0.12
1.0
0.0
15.5
0.9
0.611
0.012
72.0
1.0
289.0
6.0
1.00369
0.99007
4.01
2.74
2.0
0.33
14.9
8.4
8.0
3.0


In [ ]:
import numpy as np
url="https://raw.githubusercontent.com/Ratnakar-kaushal/Data-Science-/main/wineQualityReds.csv"
wfile=np.genfromtxt(url, delimiter=",",skip_header=2)
def choice(b):
  i=0
  if(b==1):
    while(i<13):
      print(wfile[:,i].max())
      i=i+1
  elif(b==0):
    while(i<13):
      print(wfile[:,i].min())
      i=i+1
a=int(input(a))
choice(a)

1
nan
15.9
1.58
1.0
15.5
0.611
72.0
289.0
1.00369
4.01
2.0
14.9
8.0


In [ ]:
'''
[2][2][3]=two matrix of 2*3
:,:,1 = all matrix with all rows and 1 column 
[..,1]
np.hstack=horizontal stack
np.vstack=vertical stack
random gives value between 0 and 1
np.empty is used to empty the initial array
%timeit compute_recipr=

'''

'\n[2][2][3]=two matrix of 2*3\n:,:,1 = all matrix with all rows and 1 column \n[..,1]\nnp.hstack=horizontal stack\nnp.vstack=vertical stack\nrandom gives value between 0 and 1\n\n\n'

In [ ]:
x=np.arange(5)
print("x=",x)
print("x=",x+5)
x.h

NameError: ignored